`timescale 1ns / 1ps

module imem #(
    parameter MEM_SIZE_WORDS = 256   // number of 32-bit instruction words
) (
    input  wire [31:0] addr,          // byte address, from PC (must be word-aligned)
    output wire [31:0] instr
);

    // Memory modeled as an array of 32-bit words.
    reg [31:0] mem [0:MEM_SIZE_WORDS-1];

    // Zero-initialize for deterministic simulation. On real hardware this
    // would instead be preloaded with your compiled program image (e.g. via
    // $readmemh loading a .hex file generated by the RISC-V toolchain, or
    // synthesized directly into block RAM initial contents on an FPGA).
    integer i;
    initial begin
        for (i = 0; i < MEM_SIZE_WORDS; i = i + 1) begin
            mem[i] = 32'b0;
        end
    end

    // Word-aligned indexing: drop the bottom 2 bits of the byte address.
    // addr[31:2] gives the word index; addr[1:0] would be the byte offset
    // within a word, which we ignore since every valid instruction fetch
    // is word-aligned (addr[1:0] should always be 00 in practice).
    localparam ADDR_WIDTH = $clog2(MEM_SIZE_WORDS);
    assign instr = mem[addr[ADDR_WIDTH+1:2]];

endmodule